"""add scammer report

Revision ID: 046af7c3d43a
Revises: ac40cc5a7545
Create Date: 2023-11-23 11:28:28.225310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046af7c3d43a'
down_revision = 'ac40cc5a7545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scammers_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reported_id', sa.BigInteger(), nullable=False),
    sa.Column('datetime_reported', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scammers_reports')
    # ### end Alembic commands ###
