"""Add role and user

Revision ID: 05bcfd252834
Revises: 15cf483ac3d3
Create Date: 2023-12-04 13:40:54.390650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bcfd252834'
down_revision = '15cf483ac3d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
