"""Add timezone

Revision ID: 065a2fae1bc2
Revises: 41cb4c09835d
Create Date: 2023-11-28 17:15:10.207229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065a2fae1bc2'
down_revision = '41cb4c09835d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
