"""update table name

Revision ID: 08dff8f6a0e1
Revises: 1d5f5ea0864c
Create Date: 2024-02-08 13:55:00.856786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dff8f6a0e1'
down_revision = '1d5f5ea0864c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proofs', 'moderator_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proofs', 'moderator_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
