"""Add role and user

Revision ID: 15cf483ac3d3
Revises: 
Create Date: 2023-12-04 12:38:31.537839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cf483ac3d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('datetime_create', sa.DateTime(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('answered_id', sa.BigInteger(), nullable=True),
    sa.Column('datetime_answer', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scammers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('datetime_first', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_confirmed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('number_requests', sa.Integer(), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('datetime_first', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_last', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scammers_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('datetime_reported', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('datetime_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('decision', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('reported_id', sa.BigInteger(), nullable=False),
    sa.Column('scammer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scammer_id'], ['scammers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scammers_reports_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('scammers_reports_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scammers_reports_id'], ['scammers_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scammers_reports_media')
    op.drop_table('scammers_reports')
    op.drop_table('users')
    op.drop_table('scammers')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
