"""update table name

Revision ID: 1d5f5ea0864c
Revises: f9758eea5e6e
Create Date: 2024-02-08 13:48:18.695972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5f5ea0864c'
down_revision = 'f9758eea5e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proofs', sa.Column('decision', sa.Boolean(), nullable=False))
    op.add_column('proofs', sa.Column('moderator_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proofs', 'moderator_id')
    op.drop_column('proofs', 'decision')
    # ### end Alembic commands ###
