"""Update user 4

Revision ID: 374dcb1ba67a
Revises: b125cccd9002
Create Date: 2023-11-21 13:58:03.445728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '374dcb1ba67a'
down_revision = 'b125cccd9002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('datetime_first', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('datetime_last', sa.DateTime(), nullable=True))
    op.drop_column('users', 'datetime_create')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('datetime_create', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'datetime_last')
    op.drop_column('users', 'datetime_first')
    # ### end Alembic commands ###
