"""Scammer 2

Revision ID: 5bbb4e5397e4
Revises: fb5a96b21825
Create Date: 2023-11-30 13:27:06.387341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbb4e5397e4'
down_revision = 'fb5a96b21825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scammers_reports', sa.Column('message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scammers_reports', 'message_id')
    # ### end Alembic commands ###
