"""all

Revision ID: 625aa04c8085
Revises: 
Create Date: 2024-02-08 12:50:36.013978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625aa04c8085'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('datetime_create', sa.DateTime(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('answered_id', sa.BigInteger(), nullable=True),
    sa.Column('datetime_answer', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scammers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('datetime_first', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_confirmed', sa.DateTime(), nullable=True),
    sa.Column('number_requests', sa.Integer(), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('datetime_first', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('datetime_last', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('scammer_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['scammer_id'], ['scammers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scammers_reports_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('scammer_id', sa.BigInteger(), nullable=False),
    sa.Column('proof_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scammer_id'], ['scammers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scammers_reports_media')
    op.drop_table('proofs')
    op.drop_table('users')
    op.drop_table('scammers')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
