"""Add chat_id proof

Revision ID: 64e4b89d497c
Revises: 0944d2fb3225
Create Date: 2024-01-30 11:52:19.843270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e4b89d497c'
down_revision = '0944d2fb3225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
