"""upgrade scammer report

Revision ID: 6515bd92c276
Revises: 046af7c3d43a
Create Date: 2023-11-23 11:32:22.022141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6515bd92c276'
down_revision = '046af7c3d43a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scammers_reports', sa.Column('scammer_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'scammers_reports', 'scammers', ['scammer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scammers_reports', type_='foreignkey')
    op.drop_column('scammers_reports', 'scammer_id')
    # ### end Alembic commands ###
