"""upgrade scammer

Revision ID: 6a11b378190e
Revises: bcd9234cd3a5
Create Date: 2023-11-23 14:24:57.366729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a11b378190e'
down_revision = 'bcd9234cd3a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scammers', sa.Column('is_scam', sa.Boolean(), nullable=False))
    op.add_column('scammers_reports', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    op.add_column('scammers_reports', sa.Column('reviewer_id', sa.BigInteger(), nullable=True))
    op.add_column('scammers_reports', sa.Column('datetime_reviewed', sa.DateTime(), nullable=True))
    op.add_column('scammers_reports', sa.Column('explanation', sa.String(), nullable=True))
    op.add_column('scammers_reports', sa.Column('decision', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scammers_reports', 'decision')
    op.drop_column('scammers_reports', 'explanation')
    op.drop_column('scammers_reports', 'datetime_reviewed')
    op.drop_column('scammers_reports', 'reviewer_id')
    op.drop_column('scammers_reports', 'is_reviewed')
    op.drop_column('scammers', 'is_scam')
    # ### end Alembic commands ###
