"""Add chat_id proof

Revision ID: 73c87f87c4bc
Revises: d768e3b5a208
Create Date: 2024-01-30 11:45:03.686535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c87f87c4bc'
down_revision = 'd768e3b5a208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proofs', sa.Column('chat_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proofs', 'chat_id')
    # ### end Alembic commands ###
