"""Update user

Revision ID: 800e6ced7c2a
Revises: 43de47368e63
Create Date: 2023-11-21 13:16:52.204977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800e6ced7c2a'
down_revision = '43de47368e63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=False))
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_bot')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
