"""Add user, scammer, content message

Revision ID: 83b117c5c315
Revises: 
Create Date: 2023-11-22 19:48:58.823971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b117c5c315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'answer')
    # ### end Alembic commands ###
