"""create ref table

Revision ID: 993212f56dab
Revises: 08dff8f6a0e1
Create Date: 2024-04-03 00:14:18.734368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993212f56dab'
down_revision = '08dff8f6a0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('ref_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'refs', ['ref_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'ref_id')
    op.drop_table('refs')
    # ### end Alembic commands ###
