"""Add chat_id proof

Revision ID: a870f3d9edc7
Revises: f9b63373c9cd
Create Date: 2024-01-30 12:15:17.989964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a870f3d9edc7'
down_revision = 'f9b63373c9cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proofs', sa.Column('text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proofs', 'text')
    # ### end Alembic commands ###
