"""Update contact message

Revision ID: ac40cc5a7545
Revises: 83b117c5c315
Create Date: 2023-11-23 09:11:51.731142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac40cc5a7545'
down_revision = '83b117c5c315'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('datetime_answer', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'datetime_answer')
    # ### end Alembic commands ###
