"""Update user 3

Revision ID: b125cccd9002
Revises: b27933d7eaef
Create Date: 2023-11-21 13:27:34.536369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b125cccd9002'
down_revision = 'b27933d7eaef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
