"""edit chat id field

Revision ID: b8b9256c8c77
Revises: d5bab31a1695
Create Date: 2024-04-19 21:43:27.930671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b9256c8c77'
down_revision = 'd5bab31a1695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
