"""Add scammer

Revision ID: bd09eaf82e41
Revises: 374dcb1ba67a
Create Date: 2023-11-21 17:02:58.529057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd09eaf82e41'
down_revision = '374dcb1ba67a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scammers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('datetime_first', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('number_requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scammers')
    # ### end Alembic commands ###
