"""Scammer

Revision ID: ce3ef94eb737
Revises: 065a2fae1bc2
Create Date: 2023-11-30 08:57:57.014778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3ef94eb737'
down_revision = '065a2fae1bc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scammers_reports_scammer_id_fkey', 'scammers_reports', type_='foreignkey')
    op.create_foreign_key(None, 'scammers_reports', 'scammers', ['scammer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scammers_reports', type_='foreignkey')
    op.create_foreign_key('scammers_reports_scammer_id_fkey', 'scammers_reports', 'scammers', ['scammer_id'], ['id'])
    # ### end Alembic commands ###
