"""add is_bloked to user

Revision ID: d56c789e4d02
Revises: 993212f56dab
Create Date: 2024-04-09 11:53:51.307934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56c789e4d02'
down_revision = '993212f56dab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean()))
    op.execute("UPDATE users SET is_blocked=False")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
