"""update table name

Revision ID: f9758eea5e6e
Revises: 625aa04c8085
Create Date: 2024-02-08 13:02:43.044490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9758eea5e6e'
down_revision = '625aa04c8085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('scammer_id', sa.BigInteger(), nullable=False),
    sa.Column('proof_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scammer_id'], ['scammers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scammers_reports_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scammers_reports_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scammer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('proof_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], name='scammers_reports_media_proof_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scammer_id'], ['scammers.id'], name='scammers_reports_media_scammer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scammers_reports_media_pkey')
    )
    op.drop_table('media')
    # ### end Alembic commands ###
