"""add scam media

Revision ID: faf08bef9872
Revises: 6a11b378190e
Create Date: 2023-11-23 17:53:43.052157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf08bef9872'
down_revision = '6a11b378190e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scammers_reports_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('scammers_reports_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scammers_reports_id'], ['scammers_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('scammers', 'is_scam',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scammers', 'is_scam',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('scammers_reports_media')
    # ### end Alembic commands ###
